# Build stage
FROM node:20 AS build
WORKDIR /app
COPY password-manager-frontend/package*.json ./
RUN npm install
COPY password-manager-frontend/ .
RUN npm run build

# Production stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
